apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
bases:
  - ../base
patchesStrategicMerge:
  - deployment-patch.yaml
configMapGenerator:
  - name: foodrecord-config
    behavior: merge
    literals:
      - profile=dev 