spring:
  elasticsearch:
    rest:
      uris: 43.136.179.241:9200
      connection-timeout: 5000
      read-timeout: 30000
#  kafka:
#    bootstrap-servers: 8.137.22.105:9092,8.137.22.105:9093
#    #product
#    producer:
#      retries: 0
#      batch-size: 16384
#      buffer-memory: 33554432
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    #consumer
#    consumer:
#      group-id: test-consumer-group
#      auto-offset-reset: earliest
#      enable-auto-commit: true
#      auto-commit-interval: 100
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    streams:
#      application-id: food-streams-app
#      bootstrap-servers: 8.137.22.105:9092
#      default-key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#      default-value-serde: org.apache.kafka.common.serialization.Serdes$StringSerde