spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cd-cynosdbmysql-grp-lfa6zfg0.sql.tencentcdb.com:23771/food_record?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&noAccessToProcedureBodies=false
    username: root
    password: CTct288513832##
    hikari:
      maximum-pool-size: 18   # 最大连接池数量
      minimum-idle: 10        # 最小空闲连接数量
      connection-timeout: 30000  # 连接超时时间
      idle-timeout: 600000    # 空闲连接回收时间
      max-lifetime: 1800000   # 最大连接存活时间
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    store-type: redis
    # 30 天过期
    timeout: 2592000
  elasticsearch:
    rest:
      uris: 43.136.179.241:9200
      connection-timeout: 5000
      read-timeout: 30000
  #聊天mongodb:
  # TODO 需替换配置，然后取消注释
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/food_chat
#      database: food_chat

  #MQkafka:
  # TODO 需替换配置，然后取消注释
#  kafka:
#    bootstrap-servers: localhost:9092,localhost:9093
#    #product
#    producer:
#      retries: 0
#      batch-size: 16384
#      buffer-memory: 33554432
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    #consumer
#    consumer:
#      group-id: test-consumer-group
#      auto-offset-reset: earliest
#      enable-auto-commit: true
#      auto-commit-interval: 100
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    streams:
#      application-id: food-streams-app
#      bootstrap-servers: 8.137.22.105:9092
#      default-key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#      default-value-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  messages:
    encoding: utf-8
    basename: messages

server:
  address: 0.0.0.0
  port: 800
  servlet:
    session:
      cookie:
        max-age: 2592000
        same-site: none
        secure: true
      timeout: 60m

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.foodrecord.model.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

jwt:
  secret: your_jwt_secret_key_here
  expiration: 86400000 # 24小时

security:
  jwt:
    secret: abcdefghijklmnopqrstuvwswzheathcetide
  login:
    lock-duration: 10
    max-attempts: 5
  encryption:
    key: your-encryption-key
  desensitize:
    enabled: true
    cache:
      global-rules:
        maximum-size: 1000
        expire-after-write: 3600
      scene-rules:
        maximum-size: 5000
        expire-after-write: 3600
management:
  endpoints:
    web:
      exposure:
        include: none
# 腾讯云存储相关
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx
oss:
  client:
    keyId:
    keySecret:
    endPoint:
    bucket: .

# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx

upload:
  temp:
    path: /path/to/temp/directory  # 临时文件存储路径
  video:
    path: /path/to/video/directory # 视频文件存储路径