apiVersion: v1
kind: ConfigMap
metadata:
  name: foodrecord-config
data:
  application.yml: |
    spring:
      datasource:
        url: jdbc:mysql://mysql:3306/foodrecord
        username: foodrecord
      redis:
        host: redis
        port: 6379
    logging:
      level:
        root: INFO 